### ISSUE TITLE
Plugin not working due to appending to a tuple (and simple solution)

### ISSUE THREAD

**Issue by atkdef** [stefantalpalaru/deluge-default-trackers#10]
I got this error when I started the plugin. 

[ERROR   ] 00:30:23 eventmanager:59 Event handler TorrentAddedEvent failed in <b
ound method Core.on_torrent_added of <defaulttrackers.core.Core object at 0x7fe6
b4278590>> with exception 'tuple' object has no attribute 'append'

Not sure if anyone else faces the same error. To fix this, the simple way is to change core.py Line 73:
        trackers = torrent.get_status(["trackers"])["trackers"]
to 
        trackers = list(torrent.get_status(["trackers"])["trackers"])

Hope this helps those who having the same problem.

**Comment by stefantalpalaru** [comment]
What version of Deluge were you running, with what version of Python and on what operating system?

**Comment by haarp** [comment]
I am getting the same bug on Debian 8, Python 2.7.9, Deluge 1.3.10.

**Comment by stefantalpalaru** [comment]
Please test the latest version of this plugin and let me know if it fixes your problem. I can't replicate it with Deluge 1.3.12.

**Comment by haarp** [comment]
Works now. Thanks! :)
