### ISSUE TITLE
adding multiple trackers does not work unless Deluge is running in classic mode

### ISSUE THREAD

**Issue by Phoenix09** [stefantalpalaru/deluge-default-trackers#13]
![2016-02-12_05-14-44](https://cloud.githubusercontent.com/assets/3220224/12999541/70529e52-d148-11e5-9205-7d7575795029.gif)
![2016-02-12_05-22-41](https://cloud.githubusercontent.com/assets/3220224/12999585/d3e7d7b6-d148-11e5-8224-88be7bf2850d.gif)

**Comment by Phoenix09** [comment]
after some testing it only happens if Deluge is not running in classic mode
only the first tracker that's not a duplicate is added

[deluged.txt](https://github.com/stefantalpalaru/deluge-default-trackers/files/127555/deluged.txt)
[deluge-gtk.txt](https://github.com/stefantalpalaru/deluge-default-trackers/files/127556/deluge-gtk.txt)

**Comment by seanvree** [comment]
Is this still the case? Has this been resolved?

**Comment by stefantalpalaru** [comment]
It's fixed now.
