### ISSUE TITLE
WebUI compatibility

### ISSUE THREAD

**Issue by haarp** [stefantalpalaru/deluge-default-trackers#14]
This plugin works well when configured manually, thanks for that!

But it would be great if there could a GUI for the WebUI too.

This is already on the todo list of this project. I just wanted to let you know that others could use this too :)

**Comment by Apocrathia** [comment]
Can we at least get an example configuration to use? Some of us don't even have access to a GUI to perform an initial configuration of the plugin.

**Comment by stefantalpalaru** [comment]
"~/.config/deluge/defaulttrackers.conf":

```json
{
    "file": 1,
    "format": 1
}{
    "dynamic_trackerlist_url": "https://newtrackon.com/api/stable",
    "dynamic_trackers_update_interval": 1,
    "last_dynamic_trackers_update": 1605532185,
    "trackers": [
        {
            "url": "udp://open.stealth.si:80/announce"
        },
        {
            "url": "udp://cyteam.ru:6969/announce"
        }
    ]
}
```

I've deleted most of the trackers, but you get the idea.

**Comment by Apocrathia** [comment]
Perfect! That at least gives a starting point for using the plugin in the web UI. I was originally working off of [this snippet in the source](https://github.com/stefantalpalaru/deluge-default-trackers/blob/master/defaulttrackers/core.py#L57), but I wasn't sure if the file and format keys were required.

**Comment by Subcode** [comment]
I have the egg in the plugins folder and this config in the .config folder.
Is that all i need to configure it manually? i havent noticed trackers being added.
Unfortunately i only have access to deluged with the webui.

**Comment by stefantalpalaru** [comment]
You also need to enable this plugin from somewhere.

My "~/.config/deluge/core.conf" has this in it:

```text
    "enabled_plugins": [
        "DefaultTrackers"
    ],
```

**Comment by hugalafutro** [comment]
You also need to build own image with higer version of `six` as detailed in here: https://github.com/stefantalpalaru/deluge-default-trackers/issues/35#issuecomment-756707615

To summarize, I got this working on a headless deluge running in a docker accessed via WebUI like so:
1. uploaded the `DefaultTrackers-0.2-py3.6.egg` into dir which mounts to `/config` inside the container.
2. added `DefaultTrackers` into the `enabled_plugins` array inside `core.conf` as outlined in the post above.
3. created `defaulttrackers.conf` in dir which mounts to `/config` inside the container, with this in it:

```
{
    "file": 1,
    "format": 1
}{
    "dynamic_trackerlist_url": "https://newtrackon.com/api/stable",
    "dynamic_trackers_update_interval": 1,
    "last_dynamic_trackers_update": 1610455621,
    "trackers": [
    ]
}
```
_(this will get populated by trackers when it next updates the list)_

4. built custom image according to https://github.com/stefantalpalaru/deluge-default-trackers/issues/35#issuecomment-756707615
4. recreated container with `docker-compose.yml` adjusted by commenting out `image: ` and adding `build: ./<subdir with the Dockerfile from step above>`
5. It just works ;)

**Comment by colindorrian** [comment]
If anyone finds it useful I created a simple script for formatting trackers. It saved a lot of time for me.

#!/bin/bash
urls=(
"http://www.wareztorrent.com:80/announce"
"udp://bt.xxx-tracker.com:2710/announce"
)
for url in "${urls[@]}"; do
	echo '        {'
	echo '            "url": "'$url'"'
	echo '        },'
done

**Comment by johnnyasantoss** [comment]
I guess a good starting point to implement this feature would be to look at other plugins that already have a webUI. Like https://github.com/noam09/deluge-telegramer & https://github.com/nicklan/Deluge-Pieces-Plugin

**Comment by stefantalpalaru** [comment]
Thanks, @johnnyasantoss! I looked at those and added WebUI support.

The only thing that's missing is a "refresh" button for the dynamic tracker list.
