### ISSUE TITLE
Unable to start plugin

### ISSUE THREAD

**Issue by adelphiaUK** [stefantalpalaru/deluge-default-trackers#20]
I have tried adding the plugin via the WebUI and also via the Windows Client (in non-classic mode) but the plugin will not load.

It gives no error message or anything but when you add the plugin and click apply, it just unchecks the enable box and does nothing. Not sure if there's some other error log I can look at to see the error message or not. Perhaps you can tell me if there is one or do I need to set a debug option somewhere? Right now, I can't see this plugin being operational at all.

Deluge Server running on Ubuntu 16.04 LTS **Version 1.3.15**
Deluge Client running on Windows 10 x64 **Version 1.3.15**
Default Tracker Version: **0.1 (Jul 3rd Committal)**

**Comment by stefantalpalaru** [comment]
Add the .egg file to "~/.config/deluge/plugins/" on the server, then restart the Deluge daemon.
There is no Web UI interface, so you should use a GUI client to configure it.

**Comment by adelphiaUK** [comment]
Tried that before I posted and have just tried again. It simply will not stay enabled. I don't use the WebUI normally, I use a GUI and just wanted to make sure it didn't work in the WebUI either.

**Comment by stefantalpalaru** [comment]
Is your Deluge daemon compiled with Python 2.7? Does it have a log file where you can see error messages? If you load the dynamic tracker list from a URL, do you have python-requests installed?

**Comment by adelphiaUK** [comment]
OK, I managed to resolve it. I think it was the requests that weren't installed but it gave me a shock after installing as then pip didn't work as that's for python3. You need to use pip2 for 2.7. Anyway, now I've sorted this I need to make a request for a tracker editor as some of my torrents have 160+ trackers and it's a real grind manually deleting each tracker from each torrent!
