### ISSUE TITLE
Can't find Default trackers in WebUI or file in Docker

### ISSUE THREAD

**Issue by thewinger** [stefantalpalaru/deluge-default-trackers#22]
Hi, I have Deluge installed via Docker and installed deluge-default-trackers plugin.
I have it selected in the preferences panel but it doesn't show in the preferences sidebar, even after restarting deluge.

I can't also not find the defaulttrackers.conf file inside the config folder.
Where should I look or what should I do?

**Comment by stefantalpalaru** [comment]
There is no WebUI interface for it, but it should create its config file in "~/.config/deluge/". Do you get any errors when you start Deluge in the command line?

**Comment by thewinger** [comment]
I manually created the defaulttrackers.conf in the corresponding docker/config/deluge folder, restarted Deluge container and know the torrents have the trackers list :)
