### ISSUE TITLE
downloading egg and adding plugin does not work

### ISSUE THREAD

**Issue by kkarakk** [stefantalpalaru/deluge-default-trackers#23]
i downloaded the "egg" and tried to install it. it shows up in the plugin list but am unable to activate it

**Comment by stefantalpalaru** [comment]
Run Deluge from the command line to see if there are error messages.

**Comment by Rapsoulis** [comment]
I can confirm the issue for Windows 10. 
Deluge edition: 1.3.15 (Py2.7)

**Comment by stefantalpalaru** [comment]
I got rid of the "requests" dependency, so your problem should be fixed now.
