### ISSUE TITLE
Installing egg on Windows not working

### ISSUE THREAD

**Issue by Anakist-13** [stefantalpalaru/deluge-default-trackers#24]
Hi,

I have 1.3.15 which runs on Python 2.7 on Windows 10. I can't make the plugin install. I have tried installing from the GUI, manually copying to appdata/Deluge/Plugins, and copying to program files/Deluge/deluge-1.3.15-py2.7.egg/Deluge/Plugins with no success. 

I ran deluge-debug with a log level of debug and there is no mention anywhere of Default Trackers in the output log.

Thanks.

**Comment by adelphiaUK** [comment]
Just in case you haven't, make sure the egg file goes in C:\Users\<USER>\AppData\**Roaming**\deluge\plugins (roaming being the important path here) and make sure you restart both the service AND client.

**Comment by stefantalpalaru** [comment]
Installing eggs from the Deluge GUI should place them in the correct directory, right?

Good point about restarting the Deluge server.

**Comment by adelphiaUK** [comment]
> Installing eggs from the Deluge GUI should place them in the correct directory, right?
Yes. It should but it doesn't hurt to check. If it's a windows install you know where to look.

> Good point about restarting the Deluge server.
I did mean SERVICE rather than SERVER. If you're running a separate server and connecting to that, things may be different. I always control mine from Deluge itself (if it's on Windows) and you then don't need to worry about starting the SERVICE as that is started automatically if you have it set correctly.

One important note I forgot to mention is that not all of the plugins work on the latest version of Deluge and the plugin list is far from being kept up to date, Is there a specific one you are trying to get to work? I may be able to help you out or indeed, may even tell you you're wasting your time as it doesn't work.

**Comment by ticao2** [comment]
I can not install it.

DefaultTrackers-0.1-py2.7.egg
Deluge 1.3.15
libtorrent: 1.0.11.0
Win 10 Pro

Although the file is in the correct folder.
**C:\Users\UserName\AppData\Roaming\deluge\plugins**  

The plugin does not appear in the DeLuge list.
**Edit > Preferences > Plugins**  

Should I put in this other folder?
**C:\Program Files (x86)\Deluge\deluge-1.3.15-py2.7.egg\deluge\plugins**

**Comment by stefantalpalaru** [comment]
You should install it from Deluge's graphic interface. I just tested a fresh install of Deluge-1.3.15 on a 64-bit Windows 10 Pro and it works as advertised: you add it in Preferences, you enable it in the plugin list and you configure it in its own menu entry.

Where are you getting stuck?

**Comment by ticao2** [comment]
Thanks for the quick response.  

I'll do it all over again. My Deluge interface is in **Portuguese-BR**.

I deleted the **.egg** I had placed in the folder.
**C:\Users\UserName\AppData\Roaming\deluge\plugins**
**DefaultTrackers-0.1-py2.7.egg	68.8 KB (70,537 bytes)**

I downloaded the DefaultTrackers-0.1-py2.7.egg again here:
https://github.com/stefantalpalaru/deluge-default-trackers/tree/master/egg
I clicked and selected **Save link as ...**
I saved it on my desktop.
**DefaultTrackers-0.1-py2.7.egg	80.7 KB (82,723 bytes)**
It is **different from the previous** one.

I went to Deluge in **> Preferences> Plugins> Instal-PlugIn**
Open a window **Select Plugin**
I went to where I saved the download.
I selected the file, clicked Open, and **nothing happened ...**

I closed the window. I clicked the Refresh plugins button
Default Trackers did not appear in the list of plug-ins.

Any other link where I can download?
Should I put this new file manually in the plug-in folder?

**Comment by ticao2** [comment]
I made a new download from the same source.
And it came a little different.
**DefaultTrackers-0.1-py2.7 B.egg - 80,7 KB (82.730 bytes)**

**Comment by ticao2** [comment]
I've already downloaded other plug-ins.  
There is usually a download link in the **Releases** folder, in **github**.
It might be interesting if you adopt this same method.  
Newbies like me will be able to solve it more easily. :-)

**Comment by stefantalpalaru** [comment]
> I downloaded the DefaultTrackers-0.1-py2.7.egg again here:
> https://github.com/stefantalpalaru/deluge-default-trackers/tree/master/egg
> I clicked and selected Save link as ...

There's your problem. You're supposed to click on https://github.com/stefantalpalaru/deluge-default-trackers/blob/master/egg/DefaultTrackers-0.1-py2.7.egg and then on the "Download" button.

**Comment by stefantalpalaru** [comment]
I changed the README link to point directly to the egg download.

**Comment by ticao2** [comment]
Sorry for my delay. A health problem prevented me. **It worked**.
So, first of all, thank you very much. :-)

I tried installing again using the Deluge interface, but it did not work.
Then I put the file in the folder C: \ Users \ User Name \ AppData \ Roaming \ deluge \ plugins
Did not work.
Then I put it in the folder C: \ Program Files (x86) \ Deluge \ deluge-1.3.15-py2.7.egg \ deluge \ plugins
In this case **it worked**. When I clicked refresh, it appeared in the list.
I selected it and it is now available.

Question: When will I set up two examples or list suggestions.
Are they valid?
Do you have a link where I can better understand and select a list?
Any recommendations?

**Comment by stefantalpalaru** [comment]
> When will I set up two examples or list suggestions. Are they valid?

Yes, the examples are valid. Copy/paste one of them in the "tracker list URL" field and click the "Refresh" button.
