### ISSUE TITLE
Plugin not appearing after install

### ISSUE THREAD

**Issue by theg00s3** [stefantalpalaru/deluge-default-trackers#28]
I've tried building the egg with Python 2.7 and 3.6, as well as using the provided .egg, but none of them are working on my system. They appear in the .config/deluge/plugin folder, but they don't appear at all in the plugins tab in deluge (both web-ui and thinclient)

No errors appear in the logs either

**Comment by stefantalpalaru** [comment]
What version of Python is Deluge running under?

**Comment by theg00s3** [comment]
I believe 3.6

**Comment by stefantalpalaru** [comment]
Make sure. Open the "deluge" file and see what's the interpreter on its first line.

**Comment by theg00s3** [comment]
python 3

**Comment by stefantalpalaru** [comment]
If it's "python3", then run "python3 --version" in a terminal.

**Comment by theg00s3** [comment]
Python 3.6.8

**Comment by stefantalpalaru** [comment]
Same version as I use on Gentoo. You've removed the old 0.1 plugin version, right?

**Comment by theg00s3** [comment]
yeah. The plugin folder is empty except for this one

**Comment by stefantalpalaru** [comment]
Also, try the default application mode instead of the thin client. If you're connecting to a remote deluged, then plugins need to be on the remote system and the daemon restarted.

**Comment by theg00s3** [comment]
I've got it working now. I forgot that I had a split tunnelling setup, and that the config for deluge was actually under a different user. Clicking install in deluge didn't work so I just copied the egg into the plugins folder, and it worked
