### ISSUE TITLE
Unable to enable plugin in Deluge

### ISSUE THREAD

**Issue by leekingsnatch69** [stefantalpalaru/deluge-default-trackers#29]
Windows 10 with Deluge 1.3.15 and Python 2.7.16. Getting the following error when trying to enable DefaultTrackers-0.2-py2.7.egg version of the plugin in Deluge.

DistributionNotFound: The 'six' distribution was not found and is required by the application

**Comment by stefantalpalaru** [comment]
You need this library: https://pypi.org/project/six/

**Comment by leekingsnatch69** [comment]
six is installed yet still can't enable:

c:\Python27>python -m pip search six

django-six (1.0.4)          - Django-six &#8212;&#8212; Django Compatibility
                              Library
six (1.12.0)                - Python 2 and 3 compatibility utilities
  INSTALLED: 1.12.0 (latest)

**Comment by stefantalpalaru** [comment]
You might not have the "site-packages" dir (where pip installs packages) in your PYTHONPATH. See https://stackoverflow.com/questions/25185300/cant-find-six-but-its-installed

**Comment by stefantalpalaru** [comment]
If the dependency is too much trouble, you also install the old version in the "Deluge-1.3" branch: https://github.com/stefantalpalaru/deluge-default-trackers/tree/Deluge-1.3
