### ISSUE TITLE
Please distribute a python egg for windows users

### ISSUE THREAD

**Issue by raskery** [stefantalpalaru/deluge-default-trackers#3]
Great idea! I was thinking about just this the other day as I keep on having to put in the openbittorrent tracker manually for many magnet torrents just to get some seeds/peers as utorrent is so broken these days. In fact I moved from utorrent to qbitorrent to deluge just for this feature.

Unfortunately I don't have any experience with python or with linux. It would be really helpful if you could upload a python 2.6 egg for us dumb windows users :) TIA

**Comment by stefantalpalaru** [comment]
Let me know if you still need it for Python-2.6 . Here's one for 2.7: https://github.com/stefantalpalaru/deluge-default-trackers/blob/master/egg
