### ISSUE TITLE
Py3.6 Version

### ISSUE THREAD

**Issue by adelphiaUK** [stefantalpalaru/deluge-default-trackers#33]
Is there an egg file for Deluge 2 / Python 3.6 for those of us that have no clue how to build one please? I tried renaming the file as suggested on the Deluges Plugins page and I get the DefaultTrackers plugin to show in the plugin list with a tick against it but nothing else; no DefaultTracker option to set the default trackers like in Deluge 1.3.

**Comment by stefantalpalaru** [comment]
Egg added. If it doesn't work, run the debug version of Deluge and see the output.

**Comment by zfoxzero** [comment]
> OK. I've given it a shot but as soon as I click the tick box it unchecks again almost immediately. I'm trying to run deluge with debug but for some reason, starting with debug the program never starts such that I can log in (I am using a Windows GUI to connect to Ubuntu 18.04 deluge daemon).

please check python six version ,Ubuntu 18.04 default six version is low

**Comment by adelphiaUK** [comment]
> > OK. I've given it a shot but as soon as I click the tick box it unchecks again almost immediately. I'm trying to run deluge with debug but for some reason, starting with debug the program never starts such that I can log in (I am using a Windows GUI to connect to Ubuntu 18.04 deluge daemon).
> 
> please check python six version ,Ubuntu 18.04 default six version is low

Could you explain what "python six" is? To me, python is python and I'm running 3.6.9 of that, hence why I requested this in the first place.

BTW, I still haven't managed to get it to work; still the same tick / unchecks issue.

**Comment by zfoxzero** [comment]
> > > OK. I've given it a shot but as soon as I click the tick box it unchecks again almost immediately. I'm trying to run deluge with debug but for some reason, starting with debug the program never starts such that I can log in (I am using a Windows GUI to connect to Ubuntu 18.04 deluge daemon).
> > 
> > 
> > please check python six version ,Ubuntu 18.04 default six version is low
> 
> Could you explain what "python six" is? To me, python is python and I'm running 3.6.9 of that, hence why I requested this in the first place.
> 
> BTW, I still haven't managed to get it to work; still the same tick / unchecks issue.

six is python package, view version info using `pip show six`. 
ubuntu 18.04 python3-six default version is 1.11.0-2，please pip install or upgrade six package

**Comment by adelphiaUK** [comment]
> > > > OK. I've given it a shot but as soon as I click the tick box it unchecks again almost immediately. I'm trying to run deluge with debug but for some reason, starting with debug the program never starts such that I can log in (I am using a Windows GUI to connect to Ubuntu 18.04 deluge daemon).
> > > 
> > > 
> > > please check python six version ,Ubuntu 18.04 default six version is low
> > 
> > 
> > Could you explain what "python six" is? To me, python is python and I'm running 3.6.9 of that, hence why I requested this in the first place.
> > BTW, I still haven't managed to get it to work; still the same tick / unchecks issue.
> 
> six is python package, view version info using `pip show six`.
> ubuntu 18.04 python3-six default version is 1.11.0-2，please use pip install or upgrade six package
> I used the latest version 1.15.

Yeah, I found that after googling it. However, trying to do an upgrade, it continuously comes back and says the latest version is already installed; as you say, version 1.11.02.

Interestingly, if I set python3 as the default python, pip fails with a module error. Is this expected?

As I work via a VM, I am currently building a new VM with Ubuntu 20.05.2 so this should resolve all these issues. I will came back to you.

**Comment by zfoxzero** [comment]
> > > > > OK. I've given it a shot but as soon as I click the tick box it unchecks again almost immediately. I'm trying to run deluge with debug but for some reason, starting with debug the program never starts such that I can log in (I am using a Windows GUI to connect to Ubuntu 18.04 deluge daemon).
> > > > 
> > > > 
> > > > please check python six version ,Ubuntu 18.04 default six version is low
> > > 
> > > 
> > > Could you explain what "python six" is? To me, python is python and I'm running 3.6.9 of that, hence why I requested this in the first place.
> > > BTW, I still haven't managed to get it to work; still the same tick / unchecks issue.
> > 
> > 
> > six is python package, view version info using `pip show six`.
> > ubuntu 18.04 python3-six default version is 1.11.0-2，please use pip install or upgrade six package
> > I used the latest version 1.15.
> 
> Yeah, I found that after googling it. However, trying to do an upgrade, it continuously comes back and says the latest version is already installed; as you say, version 1.11.02.
> 
> Interestingly, if I set python3 as the default python, pip fails with a module error. Is this expected?
> 
> As I work via a VM, I am currently building a new VM with Ubuntu 20.05.2 so this should resolve all these issues. I will came back to you.

https://pypi.org/project/six/

**Comment by adelphiaUK** [comment]
Finally, I'm on Ubuntu 20.04. LTS running Deluge Client 2.0.4.dev37 (Windows) and Server 2.0.3 (Ubuntu 20.04 LTS). I've come a little bit further in that the DefaultTracker checkbox now stays checked but doesn't show any configuration (despite having copied over my defaulttracker.conf file from my Deluge 1.3 VM and rebooted the server).

Anything else to suggest or can you tell me which log file I need to look in to see what the issue is.

NOTE: Ubuntu 20.04 uses Python 3.8.2

**Comment by adelphiaUK** [comment]
OK. I'm not sure what I did apart from a system reboot which surely shouldn't be required to install a plugin, but for some unknown reason it's working now so I guess this can be closed.

I'll leave it open for now in case you wish to respond.

**Comment by stefantalpalaru** [comment]
> I'm not sure what I did apart from a system reboot which surely shouldn't be required to install a plugin

You probably installed the plugin both in the Deluge daemon and the client, which is how it should be. The daemon needed to be restarted, which is what happened when you rebooted the VM.
