### ISSUE TITLE
Unable to enable plugin - unRAID

### ISSUE THREAD

**Issue by joker8656** [stefantalpalaru/deluge-default-trackers#37]
using unRAID with Deluge 2.0.3-2-201906121747-ubuntu18.04.1

If i rename the .egg to 2.0.0 itll add the plugin to the plugin list and allow me to enable it however no menu item populates in the left pane. Checking logs i see the following. 

[WARNING ][deluge.config                 :410 ] Unable to open config file /config/defaulttrackers.conf: [Errno 2] No such file or directory: '/config/defaulttrackers.conf'

**Comment by stefantalpalaru** [comment]
It's this line: https://github.com/stefantalpalaru/deluge-default-trackers/blob/0cf6f6f42ac23d7cf5fcfb1bcb59aede5c23106f/defaulttrackers/core.py#L70

Which gets the config dir's location from the system. On Linux, it's usually something like "~/.config/deluge".

unRAID's "/config" looks like a dir for system settings, which regular users might not have permission to write to. Anyway, not a plugin-related problem.

**Comment by joker8656** [comment]
How do i fix this, sorry i've no knowledge how to do it.

**Comment by stefantalpalaru** [comment]
I'm not familiar with that OS/distro, but you can set another config dir with `deluge -c /some/dir`. Make sure it exists first, and that the user Deluge runs under can write to it.

**Comment by dexn** [comment]
This is happening when using Deluge in a Docker. Many people use Dockers and it isn't limited to an OS/distro. Other plugins (WebAPI, ltConfig) I use don't have this issue when they configure themselves.

**Comment by stefantalpalaru** [comment]
Other plugins do the same thing I do:
https://github.com/nicklan/Deluge-Pieces-Plugin/blob/3d722b428296a425b6fc7166b8fc912cdc00a6be/pieces/core.py#L63
https://github.com/noam09/deluge-telegramer/blob/013240cf77be927a658836c2e589fb7b52412dcf/telegramer/core.py#L227-L228
