### ISSUE TITLE
how do i add trackers from here

### ISSUE THREAD

**Issue by aniel300** [stefantalpalaru/deluge-default-trackers#38]
how is it that i can add trackers from here ? https://github.com/ngosang/trackerslist

**Comment by stefantalpalaru** [comment]
You copy/paste a list of tracker URLs, like the one in https://github.com/ngosang/trackerslist/blob/master/trackers_all.txt

**Comment by aniel300** [comment]
right but where do i put it, i see no steps or documentation on how to do this

**Comment by stefantalpalaru** [comment]
Edit -> Preferences -> Default Trackers -> Default Trackers
