### ISSUE TITLE
Dynamic Tracker List URL Limit?

### ISSUE THREAD

**Issue by neo-neo1** [stefantalpalaru/deluge-default-trackers#39]
Would it be possible to add more than 1 URL into the "Dynamic tracker list" field? I'm using the Deluge GTK client and it only lets me input 1 URL. Would manually editing the plugin's .conf file be possible to add an additional URL list?

By the way, thanks for this great plugin.

**Comment by stefantalpalaru** [comment]
The backend expects only one URL there: https://github.com/stefantalpalaru/deluge-default-trackers/blob/0cf6f6f42ac23d7cf5fcfb1bcb59aede5c23106f/defaulttrackers/core.py#L98

A modification to make it use multiple dynamic lists needs to also do deduplication for downloaded tracker URLs.

That said, do you really need more trackers than a single list provides?
