### ISSUE TITLE
Include some trackers list in the readme as reference

### ISSUE THREAD

**Issue by ngosang** [stefantalpalaru/deluge-default-trackers#40]
Thank you for this plugin. I just added it to the recommended tools => https://github.com/ngosang/trackerslist
Are you interested in including my lists in the readme or as default in your plugin? I have been maintaining those lists for more than 7 years (30k stars in GitHub).
You can add trackon too if you want but I don't know them. I don't know if there are safe and reliable.

**Comment by stefantalpalaru** [comment]
Thanks for the list!

It's already in the UI as a label under the input field: https://github.com/stefantalpalaru/deluge-default-trackers/blob/0cf6f6f42ac23d7cf5fcfb1bcb59aede5c23106f/defaulttrackers/data/config.ui#L71

and it looks like this:

![screenshot_2022-03-27_21:24:31](https://user-images.githubusercontent.com/495550/160297387-dcafb517-8997-4c14-b288-97fdb62e4dff.png)

**Comment by ngosang** [comment]
I'm using the WebUI so I didn't notice it. What about the readme?

**Comment by stefantalpalaru** [comment]
Added to the README.

**Comment by ngosang** [comment]
Thank you!
