### ISSUE TITLE
building it got a syntax error

### ISSUE THREAD

**Issue by BIG-FAN** [stefantalpalaru/deluge-default-trackers#41]
Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
Python 2.7.16

running python setup.py bdist_egg it got a syntax error but it got build tho

byte-compiling build/bdist.linux-armv7l/egg/defaulttrackers/gtk3ui.py to gtk3ui.pyc
  File "build/bdist.linux-armv7l/egg/defaulttrackers/gtk3ui.py", line 122
    "urls": buffer.get_text(*buffer.get_bounds(), False).split(),
SyntaxError: only named arguments may follow *expression

this is from that file from line 107

def on_add(self, widget):
        try:
            options = self.generate_opts()
            for url in options["urls"]:
                if not self.in_store(url):
                    self.gtkui.store.append([url])
                    self.gtkui.trackers.append({"url": url})
            self.dialog.response(Gtk.ResponseType.DELETE_EVENT)
        except Exception as err:
            dialogs.ErrorDialog("Error", str(err), self.dialog).run()`

i am no coder i have no idea just wanna let u know :)

**Comment by stefantalpalaru** [comment]
Try using "python3" instead of "python".

**Comment by BIG-FAN** [comment]
> Try using "python3" instead of "python".

ok it work now without error and created "DefaultTrackers-0.5-py3.7.egg"
but i have Python 2.7.16 and deluge 1.3.15 i added the egg changing its name to "DefaultTrackers-0.5-py2.7.egg" and it does not get activated, it does show on the plugin list tho cant tick it

**Comment by stefantalpalaru** [comment]
If you insist on using Python2, you need a commit before January 22: https://github.com/stefantalpalaru/deluge-default-trackers/pull/36
