### ISSUE TITLE
Option to remove trackers from file

### ISSUE THREAD

**Issue by rad96** [stefantalpalaru/deluge-default-trackers#42]
Hello
Can i request an option to remove existed trackers from file before plugin add my custom tracker?

**Comment by stefantalpalaru** [comment]
You probably don't want this for all torrents, so you might as well use Deluge to edit individual torrents and delete the trackers you don't want.

**Comment by rad96** [comment]
In my use case i want this for all torrents that auto added to deluge :(

**Comment by stefantalpalaru** [comment]
There's a risk you won't find any peers on those trackers you add. That's why hanging on to the original trackers is a good idea.
