### ISSUE TITLE
Default Tracker not showing in WebUI.

### ISSUE THREAD

**Issue by aamkye** [stefantalpalaru/deluge-default-trackers#44]
Is this behavior done on purpose or some build args are needed?

```
Client: 2.1.1
Server: 2.1.1
```

**Comment by stefantalpalaru** [comment]
It's showing up for me, with Deluge-2.1.1.

Did you enable the plugin in preferences? Is the plugin egg named after the Python version you are using?

**Comment by aamkye** [comment]
what the heck :octocat: 

Due to its nature, I'm installing deluge and its plugins via CLI like:
```ansible
- name: "Clone deluge-default-trackers.git repo"
  ansible.builtin.git:
    repo: https://github.com/stefantalpalaru/deluge-default-trackers.git
    dest: /opt/deluge-default-trackers

- name: "Build deluge-default-trackers"
  ansible.builtin.shell: |
    python3 setup.py bdist_egg
  args:
    chdir: /opt/deluge-default-trackers
    executable: /bin/bash
    creates: /opt/deluge-default-trackers/dist/

- name: Copy plugin to deluge plugin folder
  ansible.builtin.shell: |
    /usr/bin/deluge-console plugin --install DefaultTrackers*.egg
  args:
    executable: /bin/bash
    chdir: /opt/deluge-default-trackers/dist/
    creates: "{{ ansible_user_dir }}/.config/deluge/plugins/DefaultTrackers*.egg"
```

And after restarting both, daemon and web it was not appearing there. But I was playing with something and it appeared. Need to dig into it.

**Comment by aamkye** [comment]
Could someone provide steps, to manually configure this plugin, without GUI?

**Comment by stefantalpalaru** [comment]
Look at the "enabled_plugins" list in "~/.config/deluge/core.conf".

In my case, it looks like this:

```yml
    "enabled_plugins": [
        "Label",
        "WebUi",
        "DefaultTrackers"
    ],
```

**Comment by stefantalpalaru** [comment]
You can simply configure it manually, through an UI, and look at the resulting config file.

**Comment by aamkye** [comment]
And now it is the best part - I don't (want to) have UI, only WebUI. I'm interested in the CLI guide and configuring it from A to Z because of the automation etc.

**Comment by stefantalpalaru** [comment]
And you don't have another computer to run a Deluge GUI on?

Here: https://gist.github.com/stefantalpalaru/1083050a76e5f7fb39f53dbde0352b59

Go away, now ;-)
