### ISSUE TITLE
Cant install default trackers

### ISSUE THREAD

**Issue by PororoManon** [stefantalpalaru/deluge-default-trackers#45]
Hi, I cant install default tracker.
> Client: 2.1.1
Server: 2.1.1
libtorrent: 2.0.10.0
python: 3.12.3

I download .egg file you attach on readmd. which for py3.9, so I rename it to py3.12 and install it. On installation, it show `[Object FileList]`. Plugin not show or installed. 
![image](https://github.com/stefantalpalaru/deluge-default-trackers/assets/148423664/00b1699b-956a-43a9-9dd4-735975db6747)

This my deluge log
![image](https://github.com/stefantalpalaru/deluge-default-trackers/assets/148423664/54752132-6b53-49c0-9209-b6f9492c25c0)

and this my `/config/plugins` `ls -l`
![image](https://github.com/stefantalpalaru/deluge-default-trackers/assets/148423664/e5ace54a-3958-41bb-82aa-9d16594869c0)

**Comment by stefantalpalaru** [comment]
This is a Deluge bug, when trying to install plugins from the Web UI: https://dev.deluge-torrent.org/ticket/3612

Workaround: install it manually by copying the "\*.egg" to your "/config/plugins" dir (and delete that "[Object FileList]" garbage).
