### ISSUE TITLE
Not showing the Menu on WebUI

### ISSUE THREAD

**Issue by ToMattBan** [stefantalpalaru/deluge-default-trackers#46]
Hey!
I'm using deluge 2.0.3 in a debian server. So far so good.
I don't use the app, just the web version, as this way I can use it in any device in my local network.

I came across your plugin and I liked it, so I downloaded the repo and builded it with the command on the README (python3 setup.py bdist_egg)
As the web installer is borked, I moved the .egg plugin to /var/lib/deluge/config/plugins (It's named DefaultTrackers-0.5-py3.11.egg here)
When I go to the WebUI, the plugin shows in the plugins list, and I then enable it there. But no new config menu shows up in the config.

![image](https://github.com/stefantalpalaru/deluge-default-trackers/assets/50156748/f30431bc-a1c8-42ed-9cef-409ae95e04ec)

Did I do something wrong? Or do it need some more config?

**Comment by stefantalpalaru** [comment]
Restart "deluged".

Also, why is the "WebUI" plugin not enabled in your screenshot?

**Comment by ToMattBan** [comment]
@stefantalpalaru restarted using "systemctl restart deluged" but no luck.

And I don't know haha. I just installed and started using, it was disabled since I started using, but, as you can see, I can access the WebUI, I don't even use the "app" version.
I also can't enable the WebUI plugin, I click on it and nothing happens

**Comment by charrus** [comment]
Change line 104 of defaulttrakcers/core.py from:

`new_trackers = [decode_bytes(url) for url in re.findall(b'\w+://[\w\-.:/]+', page) if is_url(decode_bytes(url))]`

to:

`new_trackers = [decode_bytes(url) for url in re.findall(r'\w+://[\w\-.:/]+', page) if is_url(decode_bytes(url))]`

(i.e. replace the b' with a r')

And then rebuild the egg.

**Comment by stefantalpalaru** [comment]
> (i.e. replace the b' with a r')

This makes no sense. Were you able to replicate the problem and this fixed it for you?

**Comment by charrus** [comment]
> > (i.e. replace the b' with a r')
> 
> This makes no sense. Were you able to replicate the problem and this fixed it for you?

Yeah - it fixed the issue of the missing menu entry - but looking at the logs it failed because it works on bytes not strings - so updated the fix to keep the b' and just replace `\` with `\\`.

**Comment by charrus** [comment]
If it helps this was the first error I saw which prevented the menu entry:

```
2024-07-24 20:22:20,820 DEBG 'watchdog-script' stderr output:     
/config/plugins/DefaultTrackers-0.4-py3.7.egg/defaulttrackers/core.py:104: SyntaxWarning: invalid escape sequence '\w'
```

And when changing it to `r'` gave this when adding a torrent:

```
2024-07-24 20:52:22,676 DEBG 'watchdog-script' stderr output:     
  File "/config/plugins/DefaultTrackers-0.5-py3.7.egg/defaulttrackers/core.py", line 104, in update_trackerlist_from_url            
    new_trackers = [decode_bytes(url) for url in re.findall(r'\w+://[\w\-.:/]+', page) if is_url(decode_bytes(url))]   
```

And after changing it to `\\w` and `\\-` no more errors, and trakcers are added to new torrents.

**Comment by stefantalpalaru** [comment]
I cannot get any errors with Python 3.11. You seem to be using 3.7, so maybe the Python version matters.

My version does not accept a raw string in there. It wants a simple bytestring or a raw bytestring  (`rb'...'`). I'll use the latter.
