### ISSUE TITLE
I just want the developer to read this please.

### ISSUE THREAD

**Issue by Foxwholosthistail** [stefantalpalaru/deluge-default-trackers#5]
Ok, I'm not a whiny little 16 wannabe computer nerd but why would you torment me with the trivial task of creating an egg file which would have taken your 5 seconds? I'm mainly using windows and I'm legitimately furious right now after spending the last hour on trying to learn about python and finding a way to create an egg file. I hope you can see my situation and the reasoning behind my inner rage which I'm trying to keep it that way since this is a non-profit user plugin and just because I'm a nice person. Since we've covered that I just want to say fuck you for wrecking up my nerves and congrats on the actually very useful plugin.

PS. I couldn't create the egg file still. I think I'll try that another day with my cat sitting on my lap reassuring me that everything is going to be fine. (yes, I have anger management issues.)

**Comment by stefantalpalaru** [comment]
Does this work for you: https://github.com/stefantalpalaru/deluge-default-trackers/tree/master/egg ?

**Comment by Foxwholosthistail** [comment]
Would you look at that... I wasn't actually waiting for a response but hey, you're actually a nice guy who checks his 2 years old plugin to see if an imbecile is whining about shit they could do themselves. Thanks for the file and that description which I deserve. And if I wasn't clear before, this is a really useful plugin, so thanks for that too.

Have a nicer day than mine! At least...
