### ISSUE TITLE
Manually adding trackers 

### ISSUE THREAD

**Issue by shoopdawoop** [stefantalpalaru/deluge-default-trackers#7]
What's the format to manually add trackers to defaulttrackers.conf?

GUI client crashes for me when trying to add any trackers (Deluge 1.3.11 on Mac OS X, connected to deluged running on a different machine, plugin installed via egg).

**Comment by stefantalpalaru** [comment]
Here's the content of my ~/.config/deluge/defaulttrackers.conf (on Linux):
```
{
  "file": 1,
  "format": 1
}{
  "trackers": [
    {
      "url": "udp://tracker.openbittorrent.com:80"
    },
    {
      "url": "udp://tracker.publicbt.com:80"
    },
    {
      "url": "udp://tracker.istole.it:80"
    },
    {
      "url": "udp://tracker.ccc.de:80"
    },
    {
      "url": "http://tracker.coppersurfer.tk:6969"
    }
  ]
}
```

**Comment by andrewjmetzger** [comment]
@stefantalpalaru What is the location of defaultrrackers.conf (or similar) on Windows 8? I'm using Deluge 1.3.11 and cannot find Default Trackers anywhere in the plugins list.

**Comment by stefantalpalaru** [comment]
You need to add the plugin egg first, from the Deluge settings.

For the location of the config files, see: http://dev.deluge-torrent.org/wiki/Faq#WheredoesDelugestoreitssettingsconfig

**Comment by andrewjmetzger** [comment]
@stefantalpalaru I have added the egg, and it shows up in `%APPDATA%\deluge\plugins\` (used the premade egg here).

I know where Deluge stores config, but the `defaulttrackers.config` file is not there. See screenshot:
![delugeconfdir](https://cloud.githubusercontent.com/assets/590246/7842744/340f36e6-0473-11e5-87b3-20cd23354159.PNG)

**Comment by stefantalpalaru** [comment]
Go to Edit -> Preferences -> Default Trackers in Deluge and add some trackers in the text box

**Comment by andrewjmetzger** [comment]
@stefantalpalaru There is no Default Tracker submenu. Also, note that the plugins list does not mention it. I have re-added the `.egg` file several times with no result. *See screenshot:* 
![Plugins section of Preferences dialog](https://cloud.githubusercontent.com/assets/590246/7851304/4aa0d8a4-04bb-11e5-8aa6-f4675ec7a1eb.PNG)

**Comment by shoopdawoop** [comment]
Thanks Stefan, manually editing defaulttrackers.conf worked for me.

Now is there a way to verify that these trackers are being used? Because they neither show up in Torrent>Options>Edit Trackers nor in the Trackers panel (torrents added via magnet link).

Update on the "bug" I observed: deleting and editing entries via the plugins GUI does work fine for me, only adding entries will crash the GUI each time I hit Add (in the small window where I actually enter the URL). But it does not crash the App itself and instead closes all windows. At that point I can still open the Connection Manager (Cmd-M) and get all the windows back as I left them and the newly added entry does indeed appear in the Default Trackers list.

**Comment by Maglorsmith** [comment]
Hi I'm having the same problem as Andrew above. I have tried installing both the default egg and my own and it is not showing up in either the plugins list or folder? I have tried manually putting it in the folder and scanning bu that has not worked either. Any ideas? Cheers

**Comment by stefantalpalaru** [comment]
Use the python-2.7 version of Deluge from here: http://download.deluge-torrent.org/windows/py2.7/ - I just tested it on Windows 7 and it works with the python-2.7 egg available here.

**Comment by andrewjmetzger** [comment]
Just a quick update for @Maglorsmith -- Hopefully your issue has been resolved by Stefan's posting above! If not, here is a link to the Stable/Python 2.7 releases folder. Generally, the binary (EXE) at the bottom of this page is the optimal build for use with plugins.

Link to releases with Python 2.7: http://download.deluge-torrent.org/windows/py2.7/

 Additionally, feel free to swap or add to your `defaulttrackers.conf` with my personal list (linked below),  if desired, to hasten your download speeds. 

Link: https://gist.githubusercontent.com/andrewjmetzger/c9fc3e49f2519a85a227/raw/d0eacdae4910bc388966bb41c78be044b8cfcb5f/defaulttrackers.conf

Happy torrenting!
